// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yojpttdhyfbhmuovjayc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvanB0dGRoeWZiaG11b3ZqYXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwMzE1MDYsImV4cCI6MjA4MDYwNzUwNn0.rTTHBLJ4uCxcONXLp7GZ3J7rL5BWH22BjuVbaOokrJ8";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
